name: planner_app
description: App to create Daily Goals

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  table_calendar: ^3.0.9
  flutter_time_picker_spinner: ^2.0.0
  flutter_native_splash: ^2.2.8
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


flutter_launcher_icons:
  # flutter pub run flutter_launcher_icons:main
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#303030"
    theme_color: "#FF376bb2"

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  color: "#303030" # default dark theme background color
  image: assets/icon.png
